// Created by Sekar Nagarajan (2026-09-08 15:44)
import type { ChartTokens } from "../../../theme/utils/use-portal-chart-tokens";
import type {
  DashboardReport,
  DashboardReportChartSection,
  DashboardReportKpiSection,
  DashboardReportTableSection,
} from "../../types/dashboard-export.types";
import { TABLE_ROWS_PER_SLIDE } from "./pptx-layout.constants";
import { renderChartSectionToPng } from "./report-chart-image";
import type { ReportChartContext } from "./report-chart-options";
import {
  buildReportFilename,
  chunkTableBodyRows,
  displayReportCell,
  downloadObjectUrl,
  iterateReportSections,
} from "./report-shared.utils";

export interface BuildReportPptxOptions {
  formatGeneratedAt: (isoUtc: string) => string;
  chartTokens: ChartTokens;
  formatNumber: (value: number) => string;
  formatCurrency: (value: number) => string;
}

export interface ReportPptxDownloadResult {
  filename: string;
  missingChartCount: number;
}

const SUBJECT = "E-com Dashboard Report";
const SLIDE_CX = 9144000;
const SLIDE_CY = 5143500;
const NS_A = "http://schemas.openxmlformats.org/drawingml/2006/main";
const NS_R = "http://schemas.openxmlformats.org/officeDocument/2006/relationships";
const NS_P = "http://schemas.openxmlformats.org/presentationml/2006/main";
const NS_PKG = "http://schemas.openxmlformats.org/package/2006/relationships";

export async function downloadReportPptx(
  report: DashboardReport,
  options: BuildReportPptxOptions,
): Promise<ReportPptxDownloadResult> {
  const filename = buildReportFilename(report, "pptx");
  try {
    const mod = await import("pptxgenjs");
    return await downloadWithPptxgenjs(mod.default, report, options, filename);
  } catch {
    return downloadWithFflate(report, options, filename);
  }
}

async function downloadWithPptxgenjs(
  PptxGenJS: typeof import("pptxgenjs").default,
  report: DashboardReport,
  options: BuildReportPptxOptions,
  filename: string,
): Promise<ReportPptxDownloadResult> {
  const pptx = new PptxGenJS();
  pptx.defineLayout({ name: "LAYOUT_16x9", width: 10, height: 5.625 });
  pptx.layout = "LAYOUT_16x9";
  pptx.author = report.generatedBy;
  pptx.title = report.title;
  pptx.subject = SUBJECT;
  pptx.company = SUBJECT;

  const chartContext = toChartContext(options);
  let missingChartCount = 0;
  const filterLines =
    report.appliedFilters.length > 0
      ? report.appliedFilters.map((f) => `${f.label}: ${f.value}`).join("\n")
      : "—";

  addTextSlide(pptx, report.title, [
    report.tenantName,
    `Generated by ${report.generatedBy}`,
    options.formatGeneratedAt(report.generatedAt),
    "",
    "Applied Filters",
    filterLines,
  ]);

  iterateReportSections(report, {
    onKpi: (section) => {
      addTextSlide(
        pptx,
        section.title,
        section.items.map((i) => `${i.label}: ${displayReportCell(i.value)}`),
      );
    },
    onChart: (section) => {
      const slide = pptx.addSlide();
      slide.addText(section.title, {
        x: 0.5, y: 0.28, w: 9, h: 0.4, fontSize: 18, bold: true, color: "111827", fontFace: "Arial",
      });
      const png = tryChartPng(section, chartContext);
      if (png) {
        slide.addImage({ data: png, x: 0.5, y: 0.9, w: 9, h: 4.2 });
      } else {
        missingChartCount += 1;
        slide.addText("Chart unavailable", {
          x: 0.5, y: 0.9, w: 9, h: 4.2, fontSize: 14, color: "6B7280",
          align: "center", valign: "middle", fontFace: "Arial",
        });
      }
    },
    onTable: (section) => {
      for (const chunk of chunkTableBodyRows(section.rows, TABLE_ROWS_PER_SLIDE)) {
        addTextSlide(pptx, section.title, tableLines(section, chunk));
      }
    },
  });

  await pptx.writeFile({ fileName: filename });
  return { filename, missingChartCount };
}

function addTextSlide(
  pptx: InstanceType<typeof import("pptxgenjs").default>,
  title: string,
  lines: string[],
): void {
  const slide = pptx.addSlide();
  slide.addText(`${title}\n\n${lines.join("\n")}`, {
    x: 0.5, y: 0.28, w: 9, h: 5, fontSize: 14, color: "111827", fontFace: "Arial", valign: "top",
  });
}

async function downloadWithFflate(
  report: DashboardReport,
  options: BuildReportPptxOptions,
  filename: string,
): Promise<ReportPptxDownloadResult> {
  const { zipSync, strToU8 } = await import("fflate");
  const chartContext = toChartContext(options);
  const slides: Array<{ xml: string; image?: Uint8Array }> = [];
  let missingChartCount = 0;
  let imageSeq = 0;

  const filterText =
    report.appliedFilters.length > 0
      ? report.appliedFilters.map((f) => `${f.label}: ${f.value}`).join("\n")
      : "—";
  slides.push({
    xml: textSlideXml(report.title, [
      report.tenantName,
      `Generated by ${report.generatedBy}`,
      options.formatGeneratedAt(report.generatedAt),
      "",
      "Applied Filters",
      filterText,
    ]),
  });

  iterateReportSections(report, {
    onKpi: (section: DashboardReportKpiSection) => {
      slides.push({
        xml: textSlideXml(
          section.title,
          section.items.map((i) => `${i.label}: ${displayReportCell(i.value)}`),
        ),
      });
    },
    onChart: (section: DashboardReportChartSection) => {
      const png = tryChartPng(section, chartContext);
      if (png) {
        imageSeq += 1;
        slides.push({
          xml: imageSlideXml(section.title, `rIdImg${imageSeq}`),
          image: dataUrlToBytes(png),
        });
      } else {
        missingChartCount += 1;
        slides.push({ xml: textSlideXml(section.title, ["Chart unavailable"]) });
      }
    },
    onTable: (section: DashboardReportTableSection) => {
      for (const chunk of chunkTableBodyRows(section.rows, TABLE_ROWS_PER_SLIDE)) {
        slides.push({ xml: textSlideXml(section.title, tableLines(section, chunk)) });
      }
    },
  });

  const files: Record<string, Uint8Array> = {
    "[Content_Types].xml": strToU8(contentTypesXml(slides)),
    "_rels/.rels": strToU8(ROOT_RELS),
    "docProps/core.xml": strToU8(coreXml(report)),
    "docProps/app.xml": strToU8(APP_XML),
    "ppt/presentation.xml": strToU8(presentationXml(slides.length)),
    "ppt/_rels/presentation.xml.rels": strToU8(presentationRels(slides.length)),
    "ppt/slideMasters/slideMaster1.xml": strToU8(SLIDE_MASTER),
    "ppt/slideMasters/_rels/slideMaster1.xml.rels": strToU8(MASTER_RELS),
    "ppt/slideLayouts/slideLayout1.xml": strToU8(SLIDE_LAYOUT),
    "ppt/slideLayouts/_rels/slideLayout1.xml.rels": strToU8(LAYOUT_RELS),
    "ppt/theme/theme1.xml": strToU8(THEME_XML),
  };

  let mediaIndex = 0;
  slides.forEach((slide, i) => {
    const n = i + 1;
    files[`ppt/slides/slide${n}.xml`] = strToU8(slide.xml);
    if (slide.image) {
      mediaIndex += 1;
      files[`ppt/media/image${mediaIndex}.png`] = slide.image;
      files[`ppt/slides/_rels/slide${n}.xml.rels`] = strToU8(
        slideRels(`rIdImg${mediaIndex}`, mediaIndex),
      );
    } else {
      files[`ppt/slides/_rels/slide${n}.xml.rels`] = strToU8(SLIDE_RELS);
    }
  });

  const url = URL.createObjectURL(
    new Blob([zipSync(files)], {
      type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    }),
  );
  downloadObjectUrl(url, filename);
  URL.revokeObjectURL(url);
  return { filename, missingChartCount };
}

function tableLines(
  section: DashboardReportTableSection,
  chunk: Record<string, string | number | null>[],
): string[] {
  const header = section.columns.map((c) => c.label).join(" | ");
  const body = chunk.map((row) =>
    section.columns.map((col) => displayReportCell(row[col.key])).join(" | "),
  );
  return section.footnote ? [header, ...body, "", section.footnote] : [header, ...body];
}

function toChartContext(options: BuildReportPptxOptions): ReportChartContext {
  return {
    tokens: options.chartTokens,
    formatNumber: options.formatNumber,
    formatCurrency: options.formatCurrency,
  };
}

function tryChartPng(
  section: DashboardReportChartSection,
  ctx: ReportChartContext,
): string | null {
  try {
    return renderChartSectionToPng(section, ctx);
  } catch (error) {
    console.error("[dashboard-export] chart render failed", section.id, error);
    return null;
  }
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function dataUrlToBytes(dataUrl: string): Uint8Array {
  const base64 = dataUrl.includes(",") ? dataUrl.split(",")[1]! : dataUrl;
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i);
  return bytes;
}

function paras(lines: string[]): string {
  return lines
    .map((line) => `<a:p><a:r><a:rPr lang="en-US" sz="1400"/><a:t>${escapeXml(line) || " "}</a:t></a:r></a:p>`)
    .join("");
}

function spTreeOpen(): string {
  return `<p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>`;
}

function titleShape(title: string): string {
  return `<p:sp><p:nvSpPr><p:cNvPr id="2" name="Title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="457200" y="274320"/><a:ext cx="8229600" cy="457200"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr><p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:rPr lang="en-US" sz="2200" b="1"/><a:t>${escapeXml(title)}</a:t></a:r></a:p></p:txBody></p:sp>`;
}

function textSlideXml(title: string, lines: string[]): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="${NS_A}" xmlns:r="${NS_R}" xmlns:p="${NS_P}"><p:cSld><p:spTree>${spTreeOpen()}${titleShape(title)}<p:sp><p:nvSpPr><p:cNvPr id="3" name="Body"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="457200" y="822960"/><a:ext cx="8229600" cy="4000000"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr><p:txBody><a:bodyPr wrap="square"/><a:lstStyle/>${paras(lines)}</p:txBody></p:sp></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`;
}

function imageSlideXml(title: string, embedId: string): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="${NS_A}" xmlns:r="${NS_R}" xmlns:p="${NS_P}"><p:cSld><p:spTree>${spTreeOpen()}${titleShape(title)}<p:pic><p:nvPicPr><p:cNvPr id="3" name="Chart"/><p:cNvPicPr/><p:nvPr/></p:nvPicPr><p:blipFill><a:blip r:embed="${embedId}"/><a:stretch><a:fillRect/></a:stretch></p:blipFill><p:spPr><a:xfrm><a:off x="457200" y="822960"/><a:ext cx="8229600" cy="3840480"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></p:spPr></p:pic></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`;
}

function contentTypesXml(slides: Array<{ image?: Uint8Array }>): string {
  const overrides = slides
    .map((_, i) => `<Override PartName="/ppt/slides/slide${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`)
    .join("");
  const png = slides.some((s) => s.image) ? '<Default Extension="png" ContentType="image/png"/>' : "";
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${png}<Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>${overrides}</Types>`;
}

function presentationXml(n: number): string {
  const ids = Array.from({ length: n }, (_, i) => `<p:sldId id="${256 + i}" r:id="rId${i + 1}"/>`).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="${NS_A}" xmlns:r="${NS_R}" xmlns:p="${NS_P}"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rIdMaster"/></p:sldMasterIdLst><p:sldIdLst>${ids}</p:sldIdLst><p:sldSz cx="${SLIDE_CX}" cy="${SLIDE_CY}"/><p:notesSz cx="6858000" cy="9144000"/></p:presentation>`;
}

function presentationRels(n: number): string {
  const slides = Array.from({ length: n }, (_, i) => `<Relationship Id="rId${i + 1}" Type="${NS_R}/slide" Target="slides/slide${i + 1}.xml"/>`).join("");
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="${NS_PKG}"><Relationship Id="rIdMaster" Type="${NS_R}/slideMaster" Target="slideMasters/slideMaster1.xml"/>${slides}</Relationships>`;
}

function coreXml(report: DashboardReport): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:title>${escapeXml(report.title)}</dc:title><dc:creator>${escapeXml(report.generatedBy)}</dc:creator><dc:subject>${SUBJECT}</dc:subject><cp:lastModifiedBy>${escapeXml(report.generatedBy)}</cp:lastModifiedBy></cp:coreProperties>`;
}

function slideRels(embedId: string, mediaIndex: number): string {
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="${NS_PKG}"><Relationship Id="rIdLayout" Type="${NS_R}/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="${embedId}" Type="${NS_R}/image" Target="../media/image${mediaIndex}.png"/></Relationships>`;
}

const ROOT_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="${NS_PKG}"><Relationship Id="rId1" Type="${NS_R}/officeDocument" Target="ppt/presentation.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`;

const APP_XML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>E-com Dashboard Report</Application><Company>E-com Dashboard Report</Company></Properties>`;

const SLIDE_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="${NS_PKG}"><Relationship Id="rIdLayout" Type="${NS_R}/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`;

const MASTER_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="${NS_PKG}"><Relationship Id="rId1" Type="${NS_R}/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="${NS_R}/theme" Target="../theme/theme1.xml"/></Relationships>`;

const LAYOUT_RELS = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="${NS_PKG}"><Relationship Id="rId1" Type="${NS_R}/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`;

const SLIDE_LAYOUT = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="${NS_A}" xmlns:r="${NS_R}" xmlns:p="${NS_P}" type="blank" preserve="1"><p:cSld name="Blank"><p:spTree>${spTreeOpen()}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`;

const SLIDE_MASTER = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="${NS_A}" xmlns:r="${NS_R}" xmlns:p="${NS_P}"><p:cSld><p:bg><p:bgRef idx="1001"><a:schemeClr val="bg1"/></p:bgRef></p:bg><p:spTree>${spTreeOpen()}</p:spTree></p:cSld><p:clrMap bg1="lt1" tx1="dk1" bg2="lt2" tx2="dk2" accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" hlink="hlink" folHlink="folHlink"/><p:sldLayoutIdLst><p:sldLayoutId id="2147483649" r:id="rId1"/></p:sldLayoutIdLst></p:sldMaster>`;

const THEME_XML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="${NS_A}" name="Office Theme"><a:themeElements><a:clrScheme name="Office"><a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1><a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="1F2937"/></a:dk2><a:lt2><a:srgbClr val="E5E7EB"/></a:lt2><a:accent1><a:srgbClr val="2563EB"/></a:accent1><a:accent2><a:srgbClr val="0D9488"/></a:accent2><a:accent3><a:srgbClr val="D97706"/></a:accent3><a:accent4><a:srgbClr val="DC2626"/></a:accent4><a:accent5><a:srgbClr val="7C3AED"/></a:accent5><a:accent6><a:srgbClr val="0891B2"/></a:accent6><a:hlink><a:srgbClr val="0563C1"/></a:hlink><a:folHlink><a:srgbClr val="954F72"/></a:folHlink></a:clrScheme><a:fontScheme name="Office"><a:majorFont><a:latin typeface="Arial"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont><a:minorFont><a:latin typeface="Arial"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont></a:fontScheme><a:fmtScheme name="Office"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="9525"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln><a:ln w="9525"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln><a:ln w="9525"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements></a:theme>`;
