// Modified by Sekar Nagarajan (2026-08-25 18:50)
// Lucide icon registry — central map for ecom-portal navigation and actions
import {
  AlertCircle,
  AlertTriangle,
  Anchor,
  AppWindow,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Banknote,
  Bell,
  BookOpen,
  Boxes,
  Calculator,
  Calendar,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleX,
  ClipboardList,
  Clock,
  Cloud,
  Compass,
  Contact,
  Container,
  CreditCard,
  Crown,
  DollarSign,
  Download,
  Edit,
  Ellipsis,
  Expand,
  Eye,
  EyeOff,
  FileCheck,
  FilePlus,
  FileText,
  Filter,
  Flag,
  FormInput,
  Headphones,
  History,
  Home,
  Image,
  Inbox,
  Info,
  Key,
  Landmark,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  List,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Menu,
  Minimize,
  Minus,
  Monitor,
  Moon,
  Network,
  Notebook,
  PackageCheck,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Phone,
  PictureInPicture,
  Plus,
  Printer,
  RefreshCw,
  Rocket,
  Rows,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Smartphone,
  SquarePen,
  StopCircle,
  Sun,
  Tag,
  Trash2,
  Truck,
  Type,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  Zap,
} from "lucide-react";

export const NavIcons = {
  dashboard: LayoutDashboard,
  schedules: Calendar,
  tracking: MapPin,
  rates: DollarSign,
  tariff: Tag,
  booking: BookOpen,
  shippingInstruction: ClipboardList,
  vgm: ShieldCheck,
  billOfLading: FileCheck,
  deliveryOrder: PackageCheck,
  arrivalNotice: Bell,
  containerRelease: Container,
  userCreation: UserPlus,
  vendorApprovals: CheckSquare,
  more: Ellipsis,
  admin: Settings,
  payments: Landmark,
  customerStatement: Contact,
  carbon: Cloud,
  contactUs: Headphones,
} as const;

export const Icons = {
  notebook: Notebook,
  anchor: Anchor,
  x: X,
  alert: AlertCircle,
  alertTriangle: AlertTriangle,
  appWindow: AppWindow,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowLeftRight: ArrowLeftRight,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  badgeCheck: BadgeCheck,
  banknote: Banknote,
  barcode: Container,
  container: Container,
  bell: Bell,
  bookOpen: BookOpen,
  boxes: Boxes,
  calculator: Calculator,
  calendar: Calendar,
  check: Check,
  checkCircle: CheckCircle,
  checkSquare: CheckSquare,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  circleX: CircleX,
  clipboardList: ClipboardList,
  clock: Clock,
  cloud: Cloud,
  compass: Compass,
  contact: Contact,
  creditCard: CreditCard,
  crown: Crown,
  dollarSign: DollarSign,
  download: Download,
  edit: Edit,
  ellipsis: Ellipsis,
  expand: Expand,
  eye: Eye,
  eyeOff: EyeOff,
  fileCheck: FileCheck,
  filePlus: FilePlus,
  fileText: FileText,
  filter: Filter,
  flag: Flag,
  formInput: FormInput,
  globe: Languages,
  headphones: Headphones,
  history: History,
  home: Home,
  image: Image,
  inbox: Inbox,
  info: Info,
  key: Key,
  landmark: Landmark,
  layoutDashboard: LayoutDashboard,
  layoutGrid: LayoutGrid,
  layoutList: LayoutList,
  list: List,
  lock: Lock,
  logIn: LogIn,
  logOut: LogOut,
  mail: Mail,
  mapPin: MapPin,
  menu: Menu,
  minimize: Minimize,
  minus: Minus,
  monitor: Monitor,
  moon: Moon,
  network: Network,
  packageCheck: PackageCheck,
  palette: Palette,
  panelLeftClose: PanelLeftClose,
  panelLeftOpen: PanelLeftOpen,
  phone: Phone,
  picture: PictureInPicture,
  plus: Plus,
  printer: Printer,
  refreshCw: RefreshCw,
  rocket: Rocket,
  rows: Rows,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  shieldCheck: ShieldCheck,
  ship: Ship,
  shoppingCart: ShoppingCart,
  smartphone: Smartphone,
  squarePen: SquarePen,
  stopCircle: StopCircle,
  sun: Sun,
  tag: Tag,
  team: Users,
  trash: Trash2,
  truck: Truck,
  type: Type,
  upload: Upload,
  user: User,
  userPlus: UserPlus,
  users: Users,
  zap: Zap,
} as const;
